/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SymptomSearchRouteImport } from './routes/symptom-search'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ManagerDashboardRouteImport } from './routes/manager-dashboard'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FinanceDashboardRouteImport } from './routes/finance-dashboard'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as HospitalIdRouteImport } from './routes/hospital.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSiteRouteImport } from './routes/admin.site'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminLinksRouteImport } from './routes/admin.links'
import { Route as AdminLabsRouteImport } from './routes/admin.labs'
import { Route as AdminHospitalsRouteImport } from './routes/admin.hospitals'
import { Route as AdminForbiddenRouteImport } from './routes/admin.forbidden'
import { Route as AdminCmsHospitalIdRouteImport } from './routes/admin.cms.$hospitalId'

const SymptomSearchRoute = SymptomSearchRouteImport.update({
  id: '/symptom-search',
  path: '/symptom-search',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDashboardRoute = ManagerDashboardRouteImport.update({
  id: '/manager-dashboard',
  path: '/manager-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceDashboardRoute = FinanceDashboardRouteImport.update({
  id: '/finance-dashboard',
  path: '/finance-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const HospitalIdRoute = HospitalIdRouteImport.update({
  id: '/hospital/$id',
  path: '/hospital/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSiteRoute = AdminSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLinksRoute = AdminLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLabsRoute = AdminLabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHospitalsRoute = AdminHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsHospitalIdRoute = AdminCmsHospitalIdRouteImport.update({
  id: '/cms/$hospitalId',
  path: '/cms/$hospitalId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/emergency': typeof EmergencyRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/labs': typeof LabsRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/symptom-search': typeof SymptomSearchRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/$hospitalId': typeof AdminCmsHospitalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/emergency': typeof EmergencyRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/labs': typeof LabsRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/symptom-search': typeof SymptomSearchRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/cms/$hospitalId': typeof AdminCmsHospitalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin-dashboard': typeof AdminDashboardRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/disclaimer': typeof DisclaimerRoute
  '/emergency': typeof EmergencyRoute
  '/finance-dashboard': typeof FinanceDashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/labs': typeof LabsRoute
  '/manager-dashboard': typeof ManagerDashboardRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/symptom-search': typeof SymptomSearchRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/hospitals': typeof AdminHospitalsRoute
  '/admin/labs': typeof AdminLabsRoute
  '/admin/links': typeof AdminLinksRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/site': typeof AdminSiteRoute
  '/admin/users': typeof AdminUsersRoute
  '/hospital/$id': typeof HospitalIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/cms/$hospitalId': typeof AdminCmsHospitalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/admin-dashboard'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/emergency'
    | '/finance-dashboard'
    | '/forgot-password'
    | '/labs'
    | '/manager-dashboard'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/symptom-search'
    | '/admin/forbidden'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/links'
    | '/admin/reviews'
    | '/admin/site'
    | '/admin/users'
    | '/hospital/$id'
    | '/admin/'
    | '/admin/cms/$hospitalId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin-dashboard'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/emergency'
    | '/finance-dashboard'
    | '/forgot-password'
    | '/labs'
    | '/manager-dashboard'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/symptom-search'
    | '/admin/forbidden'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/links'
    | '/admin/reviews'
    | '/admin/site'
    | '/admin/users'
    | '/hospital/$id'
    | '/admin'
    | '/admin/cms/$hospitalId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/admin-dashboard'
    | '/auth'
    | '/contact'
    | '/disclaimer'
    | '/emergency'
    | '/finance-dashboard'
    | '/forgot-password'
    | '/labs'
    | '/manager-dashboard'
    | '/profile'
    | '/reset-password'
    | '/search'
    | '/symptom-search'
    | '/admin/forbidden'
    | '/admin/hospitals'
    | '/admin/labs'
    | '/admin/links'
    | '/admin/reviews'
    | '/admin/site'
    | '/admin/users'
    | '/hospital/$id'
    | '/admin/'
    | '/admin/cms/$hospitalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminDashboardRoute: typeof AdminDashboardRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EmergencyRoute: typeof EmergencyRoute
  FinanceDashboardRoute: typeof FinanceDashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LabsRoute: typeof LabsRoute
  ManagerDashboardRoute: typeof ManagerDashboardRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SymptomSearchRoute: typeof SymptomSearchRoute
  HospitalIdRoute: typeof HospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/symptom-search': {
      id: '/symptom-search'
      path: '/symptom-search'
      fullPath: '/symptom-search'
      preLoaderRoute: typeof SymptomSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager-dashboard': {
      id: '/manager-dashboard'
      path: '/manager-dashboard'
      fullPath: '/manager-dashboard'
      preLoaderRoute: typeof ManagerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance-dashboard': {
      id: '/finance-dashboard'
      path: '/finance-dashboard'
      fullPath: '/finance-dashboard'
      preLoaderRoute: typeof FinanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/hospital/$id': {
      id: '/hospital/$id'
      path: '/hospital/$id'
      fullPath: '/hospital/$id'
      preLoaderRoute: typeof HospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/site': {
      id: '/admin/site'
      path: '/site'
      fullPath: '/admin/site'
      preLoaderRoute: typeof AdminSiteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/links': {
      id: '/admin/links'
      path: '/links'
      fullPath: '/admin/links'
      preLoaderRoute: typeof AdminLinksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/labs': {
      id: '/admin/labs'
      path: '/labs'
      fullPath: '/admin/labs'
      preLoaderRoute: typeof AdminLabsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/hospitals': {
      id: '/admin/hospitals'
      path: '/hospitals'
      fullPath: '/admin/hospitals'
      preLoaderRoute: typeof AdminHospitalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forbidden': {
      id: '/admin/forbidden'
      path: '/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/cms/$hospitalId': {
      id: '/admin/cms/$hospitalId'
      path: '/cms/$hospitalId'
      fullPath: '/admin/cms/$hospitalId'
      preLoaderRoute: typeof AdminCmsHospitalIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminHospitalsRoute: typeof AdminHospitalsRoute
  AdminLabsRoute: typeof AdminLabsRoute
  AdminLinksRoute: typeof AdminLinksRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSiteRoute: typeof AdminSiteRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCmsHospitalIdRoute: typeof AdminCmsHospitalIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminHospitalsRoute: AdminHospitalsRoute,
  AdminLabsRoute: AdminLabsRoute,
  AdminLinksRoute: AdminLinksRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSiteRoute: AdminSiteRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCmsHospitalIdRoute: AdminCmsHospitalIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminDashboardRoute: AdminDashboardRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  DisclaimerRoute: DisclaimerRoute,
  EmergencyRoute: EmergencyRoute,
  FinanceDashboardRoute: FinanceDashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LabsRoute: LabsRoute,
  ManagerDashboardRoute: ManagerDashboardRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SymptomSearchRoute: SymptomSearchRoute,
  HospitalIdRoute: HospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
